[general]
# IP address of your *axe
ip = 'replace me'

[display]
# Neofetch-like, uses 'info' and 'prin'
# Supports 16 and hex colors, bg coloring, and bold/italic/underline with chainable color tags
# '{white}', '{bg#ff00ff}', '{italic}{bgmagentabright}'
# invalid lines are ignored
format = "this is an invalid line, so its not printed :3\ninfo title\ninfo underline\ninfo \"Model\" model\ninfo \"ASIC(s)\" asicmodel\ninfo \"Firmware\" firmware\ninfo \"Uptime\" uptime\ninfo \"Best Difficulty\" bestdiff\ninfo \"Shares\" shares\ninfo \"Pool\" pool\ninfo \"Hashrate\" hashrate\ninfo \"Efficiency\" efficiency\ninfo \"Heap\" heap\n\nprin circlejerking into open source"
# Selected icon name or path
# Default: 'model'
# Values: 'none', 'vendor', 'family', 'model', path to ascii art in a plaintext file
icon = 'model'
# Spaces between the icon and the info
icon_spacing = 3
# Default: 'family'
# Values: 'vendor', 'family', 'manual'
theme = 'family'
bold_titles = true
# Separator between subtitle and info
separator = ':'
# Underline char
underline = '-'

# Supports everything display.format does
[theme]
title = 'green'
at = 'green'
underline = 'white'
subtitle = 'white'
separator = 'white'
info = 'white'

[title]
worker_name = true
hostname = true

[model]
board_version = true
family = false
vendor = false

[asicmodel]
asic_count = true
small_core_count = true

[bestdiff]
ath = false
session = false
shortpaw = ''

[efficiency]
expected = true
actual = true
shortpaw = 'off'

[firmware]
version = true

[hashrate]
expected = true
actual = true
shortpaw = 'off'

[pool]
port = true

[shares]
shortpaw = 'off'
ratio = true

[uptime]
format = '%dd %hh %mm %ss'
