[general]
# IP address of your *axe
ip = 'replace me'

[display]
# Neofetch-like, uses 'info' and 'prin'
# Supports 16 and hex colors, bg coloring, and bold/italic/underline with chainable color tags
# '{white}', '{bg#ff00ff}', '{italic}{bgmagentabright}'
# invalid lines are ignored
format = """
this is an invalid line, so its not printed :3
info title
info underline
info \"Model\" model
info \"ASIC(s)\" asicmodel
info \"Firmware\" firmware
info \"Uptime\" uptime
info \"Best Difficulty\" bestdiff
info \"Shares\" shares
info \"Pool\" pool
info \"Hashrate\" hashrate
info \"Efficiency\" efficiency
info \"Heap\" heap

prin circlejerking into open source
"""
# Selected icon name or path
# Default: 'model'
# Values: 'none', 'vendor', 'family', or path to ascii art in a plaintext file
icon = 'family'
# Spaces between the icon and the info
icon_spacing = 3
# Default: 'family'
# Values: 'vendor', 'family', 'manual', or theme name
theme = 'family'
bold_titles = true
# Separator between subtitle and info
separator = ':'
# Underline char
underline = '-'

# Supports everything display.format does
[theme]
title = 'green'
at = 'green'
underline = 'white'
subtitle = 'white'
separator = 'white'
info = 'white'
# Default icon color, if the icon doesn't specify it's own
icon = 'green'

[title]
worker_name = true
hostname = true

[model]
board_version = true
family = true
vendor = false

[asicmodel]
asic_count = true
small_core_count = true

[bestdiff]
ath = true
session = true
shortpaw = 'off'

[efficiency]
expected = true
actual = true
shortpaw = 'off'

[firmware]
version = true

[hashrate]
expected = true
actual = true
shortpaw = 'off'

[pool]
port = true

[shares]
shortpaw = 'off'
ratio = true

[uptime]
format = '%dd %hh %mm %ss'
