[general]
ip = "127.0.0.1"
separator = ":"
underline = "-"
icon = true
# default: 'model'
# values: 'vendor', 'family', 'model', path to ascii art in a plaintext file
icon_type = "model"
icon_spacing = 3

[display]
# neofetch-like, uses 'info' and 'prin'
# supports 16 colors and hex colors, wrap them in {}
# invalid lines (ones that dont start with 'info' or 'prin',
#   and ones with an invalid number of args) are ignored
format = """\
info title
info underline

info "Model" model
info "ASIC(s)" asicmodel
info "Firmware" firmware
info "Uptime" uptime
info "Best Difficulty" bestdiff
info "Shares" shares
info "Pool" pool
info "Hashrate" hashrate
info "Efficiency" efficiency
info "Heap" heap

"Settings:" 600MHz@1040mV
what else?

prin circlejerking into open source
InFo "invalid line" invalid
"""

# default: 'board'
# values: 'vendor', 'family', 'manual'
colors = "manual"
bold_titles = true

[colors]
# only used if display.colors is set to "manual"
# can be hex, or pick from the usual 16 colors + 'reset'
title = "green"
at = "white"
underline = "blackbright"
subtitle = "green"
separator = "blackbright"
info = "cyan"

[title]
worker_name = true
hostname = true

[model]
board_version = true
vendor = true # todo
family = true # todo

[asicmodel]
asic_count = true
small_core_count = true # todo/maybe, asicCount * smallCoreCount

[bestdiff]
ath = true
session = true
# off: '21M current, 210M best'
# on:  '21M/210M'
shortpaw = "off"

[efficiency]
expected = true
actual = true
shortpaw = "off"

[firmware]
version = true

[hashrate]
expected = true
actual = true
shortpaw = "off"

[pool]
port = true

[shares]
# off: '200 accepted, 4 rejected'
# on:  '200, 4'
shortpaw = "off"
# appends the accept/reject ratio % to the share string
ratio = true

[uptime]
format = "%dd %hh %mm %ss"
